spring:
  application:
    name: "pdf-ebook-converter"
  servlet:
    multipart:
      max-file-size: ${SERVLET_MAX_FILE_SIZE:10MB}
      max-request-size: ${SERVLET_MAX_REQUEST_SIZE:10MB}
  ai:
    retry:
      on-client-errors: ${OPENAI_RETRY_ON_CLIENT_ERROR}
    openai:
      chat:
        options:
          model: ${OPENAI_MODEL}
      api-key: ${OPENAI_API_KEY}
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

# spring boot actuator configuration will be set from the configMap "pdf-app-configmap-management"

resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: ${FAILURE_RATE_THRESHOLD}
        minimum-number-of-calls: ${MINIMUM_NUMBER_OF_CALLS}
        permitted-number-of-calls-in-half-open-state: ${PERMITTED_NUMBER_OF_CALLS_IN_HALF_OPEN_STATE}
        automatic-transition-from-open-to-half-open-enabled: ${AUTOMATIC_TRANSITION_FROM_OPEN_TO_HALF_OPEN_ENABLED}
        wait-duration-in-open-state: ${WAIT_DURATION_IN_OPEN_STATE}
        sliding-window-size: ${SLIDING_WINDOW_SIZE}
        sliding-window-type: ${SLIDING_WINDOW_TYPE}
    instances:
      aiPort:
        base-config: "default"

vaadin:
  launch-browser: ${VAADIN_LAUNCH_BROWSER}

logging:
  file:
    name: ${LOG_FILE_NAME}
