spring:
  application:
    name: "pdf-ebook-converter"
  servlet:
    multipart:
      max-file-size: "20MB"
      max-request-size: "20MB"
  ai:
    retry:
      on-client-errors: "true"
    openai:
      chat:
        options:
          model: "gpt-4o-mini"
      api-key: "${OPENAI_API_KEY}"

resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: "50"
        minimum-number-of-calls: "6"
        permitted-number-of-calls-in-half-open-state: "10"
        automatic-transition-from-open-to-half-open-enabled: "true"
        wait-duration-in-open-state: "15s"
        sliding-window-size: "50"
        sliding-window-type: "count_based"
    instances:
      aiPort:
        base-config: "default"

vaadin:
  launch-browser: "true"
