apiVersion: v1
kind: Secret
metadata:
  name: postgresql-credentials
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: {{ .Values.credentialsSecret.propagateToNamespaces | join "," | quote }}
data:
  # pdf-ebook-converter
  DATASOURCE_DATABASE: cGRmLWVib29rLWNvbnZlcnRlcg==
  # jdbc:postgresql://pdf-postgresql-primary.postgresql/pdf-ebook-converter
  DATASOURCE_URL: |
    amRiYzpwb3N0Z3Jlc3FsOi8vcGRmLXBvc3RncmVzcWwtcHJpbWFyeS5wb3N0Z3Jlc3FsL3BkZi1lYm9vay1jb252ZXJ0ZXI=
  # custom-postgresql-user
  DATASOURCE_USERNAME: Y3VzdG9tLXBvc3RncmVzcWwtdXNlcg==
  # custom-postgresql-user:user-password
  DATASOURCE_PASSWORD: dXNlci1wYXNzd29yZA==
  # postgres:admin-password
  DATASOURCE_ADMIN_PASSWORD: YWRtaW4tcGFzc3dvcmQ=
  # repl_user:replication-password
  DATASOURCE_REPLICATION_PASSWORD: cmVwbGljYXRpb24tcGFzc3dvcmQ=
