apiVersion: v1
kind: Secret
metadata:
  name: postgresql-credentials
data:
  # pdf-ebook-converter
  DATASOURCE_DATABASE: cGRmLWVib29rLWNvbnZlcnRlcg==
  # jdbc:postgresql://pdf-postgresql-primary/pdf-ebook-converter
  DATASOURCE_URL: |
    amRiYzpwb3N0Z3Jlc3FsOi8vcGRmLXBvc3RncmVzcWwtcHJpbWFyeS9wZGYtZWJvb2stY29udmVydGVy
  # custom-postgresql-user
  DATASOURCE_USERNAME: Y3VzdG9tLXBvc3RncmVzcWwtdXNlcg==
  # custom-postgresql-user:user-password
  DATASOURCE_PASSWORD: dXNlci1wYXNzd29yZA==
  # postgres:admin-password
  DATASOURCE_ADMIN_PASSWORD: YWRtaW4tcGFzc3dvcmQ=
  # repl_user:replication-password
  DATASOURCE_REPLICATION_PASSWORD: cmVwbGljYXRpb24tcGFzc3dvcmQ=
