apiVersion: v1
kind: Secret
metadata:
  name: pdf-postgresql-init
data:
  # CREATE USER username WITH PASSWORD 'password';CREATE DATABASE "pdf-ebook-converter" OWNER username;GRANT ALL PRIVILEGES ON DATABASE "pdf-ebook-converter" TO username;
  init-db.sql: |
    Q1JFQVRFIFVTRVIgdXNlcm5hbWUgV0lUSCBQQVNTV09SRCAncGFzc3dvcmQnO0NSRUFURSBEQVRBQkFTRSAicGRmLWVib29rLWNvbnZlcnRlciIgT1dORVIgdXNlcm5hbWU7R1JBTlQgQUxMIFBSSVZJTEVHRVMgT04gREFUQUJBU0UgInBkZi1lYm9vay1jb252ZXJ0ZXIiIFRPIHVzZXJuYW1lOwo=
