apiVersion: v1
kind: PersistentVolume
metadata:
  name: pdf-postgresql-pv
spec:
  # like a label for PersistentVolume
  storageClassName: pdf-postgresql-storage-class
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    type: DirectoryOrCreate
    path: /mnt/c/kubernetes/pdf-postgresql-storage-3
