apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-app
  labels:
    app: pdf-app
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      app: pdf-app
  template:
    metadata:
      labels:
        app: pdf-app
    spec:
      containers:
        - name: pdf-app
          image: localhost:5000/pdf-ebook-converter:0.0.16-SNAPSHOT
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 1
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 240
            periodSeconds: 5
            timeoutSeconds: 4
            failureThreshold: 3
            successThreshold: 1
          resources:
            requests:
              memory: 300Mi
              cpu: 300m
            limits:
              memory: 400Mi
              cpu: 500m
          # set environment variables from the configMap (variant 1)
          envFrom:
            - configMapRef:
                name: pdf-app-cm-main
            - secretRef:
                name: pdf-app-secret
          env:
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: file:/usr/local/apps/configuration/profiles/production/
            - name: SPRING_PROFILES_ACTIVE
              value: production
            # # set environment variables from the configMap (variant 2)
            - name: SERVLET_MAX_FILE_SIZE
              valueFrom:
                configMapKeyRef:
                  name: pdf-app-cm-servlet
                  key: SERVLET_MAX_FILE_SIZE_FROM_CM
            - name: SERVLET_MAX_REQUEST_SIZE
              valueFrom:
                configMapKeyRef:
                  name: pdf-app-cm-servlet
                  key: SERVLET_MAX_REQUEST_SIZE_FROM_CM
          # mount files with application-*.yaml from the configMap (variant 3) and use them in the application (profile "production")
          volumeMounts:
            - name: pdf-app-cm-production-profile
              mountPath: /usr/local/apps/configuration/profiles/production
              readOnly: true
      # mount files with application-*.yaml from the configMap (variant 3) and use them in the application (profile "production")
      volumes:
        - name: pdf-app-cm-production-profile
          configMap:
            name: pdf-app-cm-production-profile
            items:
              - key: application-production.yaml
                path: application-production.yaml
