apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pdf-app
  namespace: default
spec:
  minReplicas: 1
  maxReplicas: 6
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 100
          type: Utilization
      type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pdf-app
