apiVersion: v1
kind: Secret
metadata:
  name: pdf-app-secret
data:
  # jdbc:postgresql://pdf-postgresql-0.pdf-postgresql-svc,pdf-postgresql-1.pdf-postgresql-svc,pdf-postgresql-2.pdf-postgresql-svc/pdf-ebook-converter
  DATASOURCE_URL: |
    amRiYzpwb3N0Z3Jlc3FsOi8vcGRmLXBvc3RncmVzcWwtMC5wZGYtcG9zdGdyZXNxbC1zdmMscGRmLXBvc3RncmVzcWwtMS5wZGYtcG9zdGdyZXNxbC1zdmMscGRmLXBvc3RncmVzcWwtMi5wZGYtcG9zdGdyZXNxbC1zdmMvcGRmLWVib29rLWNvbnZlcnRlcgo=
  DATASOURCE_USERNAME: dXNlcm5hbWU=
  DATASOURCE_PASSWORD: cGFzc3dvcmQ=
  OPENAI_API_KEY: |
    <placeholder for OpenAI API key>
