apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-app
  labels:
    app: pdf-app
spec:
  replicas: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      app: pdf-app
  template:
    metadata:
      labels:
        app: pdf-app
    spec:
      containers:
        - name: pdf-app
          image: localhost:5000/pdf-ebook-converter:0.0.13-SNAPSHOT
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 240
            periodSeconds: 5
          resources:
            requests:
              memory: 300Mi
              cpu: 300m
            limits:
              memory: 400Mi
              cpu: 500m
          # set environment variables from the configMap (variant 1)
          envFrom:
            - configMapRef:
                name: pdf-app-configmap-main
            - secretRef:
                name: pdf-app-secret
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production,management
            # # set environment variables from the configMap (variant 2)
            - name: SERVLET_MAX_FILE_SIZE
              valueFrom:
                configMapKeyRef:
                  name: pdf-app-configmap-servlet-multipart
                  key: SERVLET_MAX_FILE_SIZE_FROM_CM
            - name: SERVLET_MAX_REQUEST_SIZE
              valueFrom:
                configMapKeyRef:
                  name: pdf-app-configmap-servlet-multipart
                  key: SERVLET_MAX_REQUEST_SIZE_FROM_CM
          # mount files with application-*.properties from the configMap (variant 3) and use them in the application (profile "management")
          volumeMounts:
            - name: pdf-app-configmap-management
              mountPath: /usr/local/apps/configuration
              readOnly: true
      # mount files with application-*.properties from the configMap (variant 3) and use them in the application (profile "management")
      volumes:
        - name: pdf-app-configmap-management
          configMap:
            name: pdf-app-configmap-management
            items:
              - key: application-management.properties
                path: application-management.properties
