apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-app
  labels:
    app: pdf-app
spec:
  replicas: 3
  minReadySeconds: 30
  selector:
    matchLabels:
      app: pdf-app
  template:
    metadata:
      labels:
        app: pdf-app
    spec:
      containers:
        - name: pdf-app
          image: localhost:5000/pdf-ebook-converter:0.0.9-SNAPSHOT
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 240
            periodSeconds: 5
          resources:
            requests:
              memory: 300Mi
              cpu: 300m
            limits:
              memory: 400Mi
              cpu: 500m
