apiVersion: v1
kind: Secret
metadata:
  name: postgresql-credentials
data:
  # pdf-ebook-converter
  DATASOURCE_DATABASE: cGRmLWVib29rLWNvbnZlcnRlcg==
  # jdbc:postgresql://pdf-postgresql-primary-0.pdf-postgresql-primary,pdf-postgresql-read-0.pdf-postgresql-read,pdf-postgresql-read-1.pdf-postgresql-read/pdf-ebook-converter
  DATASOURCE_URL: |
    amRiYzpwb3N0Z3Jlc3FsOi8vcGRmLXBvc3RncmVzcWwtcHJpbWFyeS0wLnBkZi1wb3N0Z3Jlc3FsLXByaW1hcnkscGRmLXBvc3RncmVzcWwtcmVhZC0wLnBkZi1wb3N0Z3Jlc3FsLXJlYWQscGRmLXBvc3RncmVzcWwtcmVhZC0xLnBkZi1wb3N0Z3Jlc3FsLXJlYWQvcGRmLWVib29rLWNvbnZlcnRlcgo=
  # custom-postgresql-user
  DATASOURCE_USERNAME: Y3VzdG9tLXBvc3RncmVzcWwtdXNlcgo=
  # custom-postgresql-user:user-password
  DATASOURCE_PASSWORD: dXNlci1wYXNzd29yZAo=
  # postgres:admin-password
  DATASOURCE_ADMIN_PASSWORD: YWRtaW4tcGFzc3dvcmQK
  # repl_user:replication-password
  DATASOURCE_REPLICATION_PASSWORD: cmVwbGljYXRpb24tcGFzc3dvcmQK
